### ISSUE TITLE
Multiple Galaxy instances, multiple config files

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/gravity#13]
I started writing Gravity as a way to control a Galaxy servers. Then it quickly became a tool for managing an entire Galaxy instance with multiple config files, much like we have for usegalaxy.org. It then grew to be a tool to encompass multiple instances, so you could use one Gravity to control all of your Galaxies (on a single host, anyway). Although a lot of this is unfinished and sitting in the cli_instance_config branch.

That latter concept of multiple instance support could be useful in development. And there are sites running two production Galaxy instances from the same box, probably as the same user. But it does add some amount of complexity to dealing with the Gravity command line.

Perhaps it would be better to hide away all of the multiple instance complexity unless it's the case that you have created more than one instance. Or perhaps it'd be better to drop multiple instance support entirely.

Finally, I like the way that @jmchilton has added `pulsar*` commands to Pulsar as part of the Pythonic (`setup.py`) install, and I kind of think we ought to ship a `galaxy` command directly with Galaxy, either as Gravity installed as a dependency of Galaxy, some trimmed down version of Gravity, or something entirely separate from Gravity.

All that said, time to get back to work on Gravity and make it stable. =)

**Comment by dannon** [comment]
Definitely want to keep it focused on the single host?  I'd started building a cloudman CLI (where I first played with Click, hence those recommendations) and it'd make sense to roll that functionality in here instead of bioblend, IMO.

**Comment by natefoo** [comment]
So you're saying the scope should be larger and not smaller? =)

**Comment by dannon** [comment]
Exactly!
