### ISSUE TITLE
Foreground start and logging

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/gravity#29]
From @natefoo :

> galaxyctl start probably needs a -n flag to allow for logging to go to log files instead of stdout/stderr, but non-daemonization. This makes it more usable for system init tools (e.g. systemd).

Would that command be tailing the logs into a single file ? Is that compatible with following the logs using `journalctl` ? Would the exisiting `log_dir` option not be sufficient ?

**Comment by mvdbeek** [comment]
I don't know how I was able to misread that ... I'll do that real quick

**Comment by natefoo** [comment]
Supervisor already writes the logs individually in `log_dir`. `galaxy` (or `galaxyctl start -f`) just runs `tail` across multiple files to write them to the terminal.

If admins want the full log output in journald, they can just run `galaxy` (or `galaxyctl start -f`). If they don't want to replicate to journald, that's what the `-n` option would be for. Then they'd just get `supervisord`'s output in `journald`.

**Comment by mvdbeek** [comment]
Added this as the `--quiet` option in https://github.com/galaxyproject/gravity/pull/40
