### ISSUE TITLE
Resolving symlinks hides galaxy_root

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/gravity#30]
The config file path is resolved [here](https://github.com/galaxyproject/gravity/blob/main/gravity/options.py#L22) (by Click) and [here](https://github.com/galaxyproject/gravity/blob/main/gravity/state.py#L139), in both cases via `os.path.realpath`. Thus, if it were initially a symlink, we lose the symlink's parent. As a result, [code like this](https://github.com/galaxyproject/gravity/blob/main/gravity/config_manager.py#L121) breaks because `pardir` value is incorrect.

I don't have a proposed solution (still getting acquainted with gravity), but I suspect we are resolving those paths too early and too unconditionally: the symlink's path may be useful. Also, it seems to me gravity should assume we are running from `galaxy_root` if that value is not explicitly provided.

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/gravity/pull/31 ?
