### ISSUE TITLE
Check consistency of supervisor config

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/gravity#43]
and re-write if possible. If you update from galaxy.yml.sample to galaxy.yml we rewrite the gravity config, but not the supervisor config, which still refers to the old config file (galaxy.yml.sample), so unless you also change something in the gravity section you're still starting from the old sample. We can probably use the recorded gravity version in the gravity config to not do this unnecessarily.

**Comment by natefoo** [comment]
This was fixed in one of the 0.x releases, but also is irrelevant now that 1.x has no configstate.
