### ISSUE TITLE
slurm drmaa env variable setting?

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/gravity#52]
When running Galaxy using a DRMAA system, Galaxy needs to know where to find the drmaa libraries.

The DRMAA_LIBRARY_PATH environment variable needs to be included in the supervisor setup for Galaxy. At the moment there seems no way for Gravity to pick up extra environment variables and add them to the running environment in supervisord.

This is especially required for job handlers (standalone) started by gravity. I imagine that it may also be required by gunicorn as in some setups it may also be handling jobs.

**Comment by Slugger70** [comment]
The only way I can think of short of modifying gravity code is by doing some post ansible hacks into the supervisor files.

**Comment by natefoo** [comment]
You can set them in the environment that supervisord is started in (e.g. systemd). But I am working on the ability to directly set them for each component.

**Comment by hexylena** [comment]
@Slugger70 what do you reckon, we can just leave that bit of it alone then and then this isn't a priority as much?

**Comment by natefoo** [comment]
Oh it is also worth mentioning that this is configurable in the job config as a runner plugin param (`drmaa_library_path`).

Anyway, it seems I spoke too soon... #61
