### ISSUE TITLE
Don't SIGHUP gunicorn to gracefully reload when the app is preloaded

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/gravity#54]
[Per the docs](https://docs.gunicorn.org/en/stable/signals.html):

> `HUP`: Reload the configuration, start the new worker processes with a new configuration and gracefully shutdown older workers. If the application is not preloaded (using the preload_app option), Gunicorn will also load the new version of it.

So sending a `HUP` to a preloaded application doesn't actually result in a restart.

**Comment by mvdbeek** [comment]
`USR2` should be used then. gunicornherder should handle that already in https://github.com/alphagov/unicornherder/blob/master/unicornherder/herder.py#L245

**Comment by natefoo** [comment]
This is for non-unicornherder deployments (since we already disabled preload for unicornherder), but if we have Gravity manage the `USR2` and later `TERM`, we've basically duplicated the unicornherder functionality directly in Galaxy. Which maybe is a reasonable thing for us to do?
