### ISSUE TITLE
Zero downtime restarts

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/gravity#74]
Currently we're relying on [unicornherder](https://github.com/alphagov/unicornherder/) to perform zero-downtime restarts, but this has a few drawbacks. We have patches for some of the biggest issues we're running in to (alphagov/unicornherder#38, alphagov/unicornherder#39) and others that we don't (galaxyproject/galaxy#14625) but as unicornherder seems to not be seeing much activity these days, we would like to consider alternatives.

One option is to try to support `SIGUSR2` restarts with gunicorn directly in Gravity, but you still need some kind of background process management since as far as I know, you cannot keep gunicorn directly attached in the foreground to systemd/supervisord after the `SIGUSR2` restart cycle completes, as discssed in benoitc/gunicorn#2856.

However, in discussion with @hexylena, it seems like we can use the solution that EU was using with uWSGI. On org, I was using [uWSGI Zerg Mode](https://uwsgi-docs.readthedocs.io/en/latest/Zerg.html) to run one zergling at a time, bringing up a second whenever a restart was needed. Bringing up the second signaled the first to shut down, and then things continued normally from there. So at any given time you had one or the other zergling running, but not both.

On EU, they run multiple zerglings run at all times. When a restart is needed, one zergling is restarted, and once that zergling has fully reloaded and is accepting requests, the next zergling is restarted, and so on.

In the case of Gravity, I believe we should be able to have systemd open the socket, and then run two gunicorn workers that use the same fd-over-socket method used by Zerg Mode and [circusd](https://circus.readthedocs.io/en/latest/for-ops/sockets/) (which was actually the initial way we ran gunicorn in development prior to 22.01...). Gravity then will just need to manage the restart dance.

The only thing I don't like about this scenario is that under supervisord, you have two logfiles, one for each worker, which is kind of a bummer. But this is mitigated in a systemd setup where everything logs to journald, so you can just request the combined logs using a journalctl unit matching pattern.

**Comment by natefoo** [comment]
So the idea of running a zerg-mode-like thing didn't really fly since I made the (incorrect) assumption that fd inheritance just magically balances connections, but it doesn't - the uWSGI zerg pool server, while [admittedly very small](https://github.com/unbit/uwsgi/blob/master/plugins/zergpool/zergpool.c) does perform a service here we'd need to replicate to do that exactly.

Last week,@mira-miracoli got this working for usegalaxy.eu using nginx load balancing (multiple `server`s in an `upstream`), which works quite well. We discussed some fancier solutions that don't rely on nginx (where you might see some timeouts or long blocking before moving to the next upstream when one goes down) e.g. with traefik, which are probably worth consideration but aren't really issues for Gravity, I am just mentioning them here so we don't forget. I am not sure how the restart process is managed currently (by hand, or repurposing [gxadmin uwsgi zerg-swap](https://github.com/galaxyproject/gxadmin/blob/3edc704aadb412fcb2771dc83eddd406cc5b9748/parts/24-uwsgi.sh#L144) but that's roughly what we should add to the `galaxyctl graceful` process.

**Comment by natefoo** [comment]
Right, that's another big win. Combined with the systemd support, we could also just create a systemd socket listening to ports 80/443, forward that to traefik, and not use nginx at all.

**Comment by mvdbeek** [comment]
Still need nginx for static proxying and mod-zip (mod-zip we could conceivably replace with another service).

**Comment by natefoo** [comment]
Ah I see traefik doesn't serve static files at all, that's a bummer. We could of course use another service, but perhaps it makes the most sense to keep nginx for this.

**Comment by mira-miracoli** [comment]
We are currently thinking about using two headnodes, so we have no downtime during OS upgrades etc.
For that we could use traefik2 as proxy and loadbalancer.. Its sad that we have the static file problem, I like traefik, too

**Comment by hexylena** [comment]
> We are currently thinking about using two headnodes, so we have no downtime during OS upgrades etc.

I used to do that, had haproxy sitting on a VM in front of the actual head node (and other machines), but the cloud was too unreliable. 

> Ah I see traefik doesn't serve static files at all, that's a bummer. We could of course use another service, but perhaps it makes the most sense to keep nginx for this.

Yeah, why not nginx + traefik? Traefik to handle the backends/load balancing over them, and then nginx for static file support? It'd be a *very* easy upgrade path for most users: just replace the gunicorn address with gravity-managed traefik, and you get zero downtime support. And for laptop-use case, traefik handles all traffic.

**Comment by natefoo** [comment]
Implemented in #81.
