### ISSUE TITLE
timeline for 1.x release?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/gravity#92]
Hey y'all,

just wanted to check in on the timeline for the 1.x release, just so I can get started updating the trainings with the new systemd setup.

no rush or nothing, no pressure.

**Comment by nsoranzo** [comment]
Would be good to have 1.0 out also on the Galaxy side, so we can reconcile its `lib/galaxy/dependencies/pinned-requirements.txt` (which is currently pinned to `git+https://github.com/galaxyproject/gravity.git@release_1.x`) with `pyproject.toml` (which still has `">=0.10.0"`).

**Comment by sveinugu** [comment]
@natefoo If it is not too late, and if Gravity 1.0 will not be a part of the current release, it would be nice if PR https://github.com/galaxyproject/gravity/pull/96 would be merged (with version bump), as it works together with two other PRs, one in galaxy (https://github.com/galaxyproject/galaxy/pull/15147), and one in gx-it-proxy (https://github.com/galaxyproject/gx-it-proxy/pull/14), which have both been merged.

**Comment by mvdbeek** [comment]
gravity 1 is part of the release branch, we just need a formal release here.

**Comment by natefoo** [comment]
I can work on getting it merged and release another 0.x version for 22.05 servers before merging it forward to 1.x for 23.0.

**Comment by sveinugu** [comment]
No need for a 22.05 release, or if so, the other related PMs should also be backported. But I don't think there is a need for that as there is a nginx workaround for previous releases. Having this as part of 1.0 in 23.0 is perfect, just didn't know if that was the plan or not.

**Comment by sveinugu** [comment]
But if that is the best merge strategy for 23.0 then by all means go ahead!

**Comment by natefoo** [comment]
https://github.com/galaxyproject/gravity/releases/tag/v1.0.0

The package was pushed to Test PyPI but the Main PyPI task was skipped, presumably by [this conditional](https://github.com/galaxyproject/gravity/blob/85515cb70bcc0275654a6ddb769ccf78a8d30eb4/.github/workflows/publish.yaml#L34), I guess because I was republishing the release instead of creating it? I'm just going to push from the command line I guess.

**Comment by natefoo** [comment]
Ok, uploaded and released to PyPI. For the record I downloaded the dist/wheel from Test PyPI and uploaded that with twine, so they are the same artifacts as built in GHA.

@sveinugu I am circling back to your PR now and that will be 1.0.1 and maybe 0.13.7 as well if I decide to merge it that way. Sorry for the delays and thanks all.

**Comment by natefoo** [comment]
Ah yeah ok, I understand that the reason we don't need this for 22.05 is because the corresponding fixes are only for 23.0+.
